#!/usr/bin/env python3
"""Author crate solids as native XY cells/free spans; no mesh or visual-only cap.
Preserves original portal indices by keeping each first split aperture in place.
"""
import copy,json
from pathlib import Path
p=Path(__file__).with_name('dust2.re2dmap');d=json.loads(p.read_text())
ws=[w for w in d['walls'] if w.get('tag')=='crate'];boxes=[]
for i in range(0,len(ws),4):
 group=ws[i:i+4];pts=[p for w in group for p in (w['from'],w['to'])]
 boxes.append((min(v[0] for v in pts),min(v[1] for v in pts),max(v[0] for v in pts),max(v[1] for v in pts),group[0]['bottom'],group[0]['top']))
parts={};out=[]
for c in d['cells']:
 x,y,w,h=c['rect'];hit=[b for b in boxes if b[0]<x+w and b[2]>x and b[1]<y+h and b[3]>y]
 xs=sorted({x,x+w,*[v for b in hit for v in (b[0],b[2]) if x<v<x+w]});ys=sorted({y,y+h,*[v for b in hit for v in (b[1],b[3]) if y<v<y+h]})
 parts[c['id']]=[]
 for yy,y2 in zip(ys,ys[1:]):
  for xx,x2 in zip(xs,xs[1:]):
   n=copy.deepcopy(c);n['id']=c['id'] if not parts[c['id']] else c['id']+'_box'+str(len(parts[c['id']]));n['rect']=[xx,yy,x2-xx,y2-yy]
   b=next((b for b in hit if b[0]<=xx and x2<=b[2] and b[1]<=yy and y2<=b[3]),None)
   if b:
    spans=[]
    for s in n['spans']:
     if s['bottom']>=b[5] or s['top']<=b[4]:spans.append(s);continue
     if s['bottom']<b[4]:low=copy.deepcopy(s);low['top']=b[4];spans.append(low)
     if s['top']>b[5]:high=copy.deepcopy(s);high['bottom']=b[5];high['floorColor']='#ab7850';spans.append(high)
    n['spans']=spans
   parts[c['id']].append(n);out.append(n)
def intervals(a,b,openings):
 return [{'bottom':max(sa['bottom'],sb['bottom'],o['bottom']),'top':min(sa['top'],sb['top'],o['top'])} for sa in a['spans'] for sb in b['spans'] for o in openings if min(sa['top'],sb['top'],o['top'])>max(sa['bottom'],sb['bottom'],o['bottom'])]
def edge(a,b):
 x,y,w,h=a['rect'];u,v,ww,hh=b['rect']
 if x+w==u or u+ww==x:
  lo,hi=max(y,v),min(y+h,v+hh);co=max(x,u)
  if hi>lo:return [co,lo],[co,hi]
 if y+h==v or v+hh==y:
  lo,hi=max(x,u),min(x+w,u+ww);co=max(y,v)
  if hi>lo:return [lo,co],[hi,co]
ports=[];extra=[]
for old in d['portals']:
 variants=[]
 for a in parts.get(old['cellA'],[{'id':old['cellA']} ]):
  for b in parts.get(old['cellB'],[{'id':old['cellB']} ]):
   if 'rect' not in a or 'rect' not in b:
    # Slopes are generated by SDK, not authored portal endpoints in this map.
    raise ValueError('unexpected non-cell explicit portal')
   e=edge(a,b)
   if not e:continue
   axis=1 if e[0][0]==e[1][0] else 0;other=1-axis
   if e[0][other]!=old['from'][other]:continue
   lo=max(e[0][axis],min(old['from'][axis],old['to'][axis]));hi=min(e[1][axis],max(old['from'][axis],old['to'][axis]))
   op=intervals(a,b,old['openings'])
   if hi<=lo or not op:continue
   n=copy.deepcopy(old);n['cellA']=a['id'];n['cellB']=b['id'];n['from']=e[0][:];n['to']=e[1][:];n['from'][axis]=lo;n['to'][axis]=hi;n['openings']=op;variants.append(n)
 if not variants:raise ValueError('portal became empty '+old['id'])
 ports.append(variants[0])
 for i,n in enumerate(variants[1:]):n['id']=old['id']+'_box'+str(i);extra.append(n)
for group in parts.values():
 for i,a in enumerate(group):
  for b in group[:i]:
   e=edge(a,b)
   if e:
    op=intervals(a,b,[{'bottom':-100000,'top':100000}])
    if op:extra.append({'id':'box_air_'+str(len(extra)),'cellA':a['id'],'cellB':b['id'],'from':e[0],'to':e[1],'openings':op,'door':False})
d['cells']=out;d['portals']=ports+extra;p.write_text(json.dumps(d,indent=2)+'\n');print('crate solids',len(boxes),'cells',len(out),'portals',len(d['portals']))
