# Only the binaural DSP is consumed. Re2D topology remains authoritative.
option(R2D_ENABLE_STEAM_AUDIO "Steam Audio HRTF in existing SDL_mixer" ON)
set(R2D_STEAM_AUDIO_SDK "" CACHE PATH "Extracted Steam Audio SDK root (contains include/ and lib/)")
if(R2D_ENABLE_STEAM_AUDIO AND NOT EMSCRIPTEN)
    if(APPLE AND CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(_r2d_sa_platform osx)
        set(_r2d_sa_lib libphonon.dylib)
    elseif(WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_r2d_sa_platform windows-x64)
        set(_r2d_sa_lib phonon.dll)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64" AND CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_r2d_sa_platform linux-x64)
        set(_r2d_sa_lib libphonon.so)
    endif()
    if(_r2d_sa_platform)
        if(NOT R2D_STEAM_AUDIO_SDK)
            include(FetchContent)
            FetchContent_Declare(r2d_steam_audio
                URL https://github.com/ValveSoftware/steam-audio/releases/download/v4.8.1/steamaudio_4.8.1.zip
                URL_HASH SHA256=4a0aa5ec1176f38f0b0993a37c2259d9e86f27e22d5e24f83ec4c3cb9a1d5449)
            FetchContent_MakeAvailable(r2d_steam_audio)
            set(R2D_STEAM_AUDIO_SDK "${r2d_steam_audio_SOURCE_DIR}")
            if(EXISTS "${R2D_STEAM_AUDIO_SDK}/steamaudio/include/phonon.h")
                string(APPEND R2D_STEAM_AUDIO_SDK "/steamaudio")
            endif()
        endif()
        add_library(R2D_SteamAudio SHARED IMPORTED GLOBAL)
        set_target_properties(R2D_SteamAudio PROPERTIES
            IMPORTED_LOCATION "${R2D_STEAM_AUDIO_SDK}/lib/${_r2d_sa_platform}/${_r2d_sa_lib}"
            INTERFACE_INCLUDE_DIRECTORIES "${R2D_STEAM_AUDIO_SDK}/include")
        if(WIN32)
            set_target_properties(R2D_SteamAudio PROPERTIES IMPORTED_IMPLIB "${R2D_STEAM_AUDIO_SDK}/lib/windows-x64/phonon.lib")
        endif()
        set(R2D_STEAM_AUDIO_RUNTIME "${R2D_STEAM_AUDIO_SDK}/lib/${_r2d_sa_platform}/${_r2d_sa_lib}")
    else()
        message(STATUS "Steam Audio HRTF unavailable on this target; explicit non-HRTF world audio remains")
    endif()
endif()
